server:
  port: 8091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: guest
    password: guest

management:
  health:
    rabbit:
      enabled: false

logging:
  file:
    name: ../common-module/medical.log
